'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Friend NotInheritable Class TimeManager
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As TimeManager = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New TimeManager()),TimeManager)
    
    Public Shared ReadOnly Property [Default]() As TimeManager
        Get
            Return defaultInstance
        End Get
    End Property
End Class
